# api/species_data.py
#
# Base de datos de Anfibios y Reptiles de Costa Rica
# Fuente de verdad para el backend de Anur-App
# Importada por api/public.py

SPECIES = [

    # ═══════════════════════════════════════════════════
    #  ANFIBIOS — Ranas (Anura)
    # ═══════════════════════════════════════════════════

    {
        "id": "agalychnis-callidryas",
        "categoria": "anfibio",
        "subcategoria": "rana",
        "nombre_comun_es": "Rana Roja",
        "nombre_comun_en": "Red-eyed Tree Frog",
        "nombre_cientifico": "Agalychnis callidryas",
        "familia": "Phyllomedusidae",
        "orden": "Anura",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": False,
        "nocturna": True,
        "arborea": True,
        "habitats": ["bosque_humedo", "manglar", "rio"],
        "regiones_cr": ["Caribe", "Pacífico Central", "Pacífico Sur", "Zona Norte"],
        "altitud_min": 0,
        "altitud_max": 1100,
        "longitud_max_cm": 7.5,
        "descripcion": "Ícono de Costa Rica y del bosque tropical. Sus enormes ojos rojos con pupilas verticales la hacen inconfundible.",
        "curiosidad": "Sus huevos detectan las vibraciones de lluvia y de serpientes para eclosionar antes de tiempo y caer al agua.",
        "imagen": "agalychnis_callidryas.jpg",
        "tags": ["icónica", "colorida", "fotografiable", "nocturna", "rana de árbol"],
    },
    {
        "id": "agalychnis-annae",
        "categoria": "anfibio",
        "subcategoria": "rana",
        "nombre_comun_es": "Rana de Árbol Ojos Azules",
        "nombre_comun_en": "Blue-sided Tree Frog",
        "nombre_cientifico": "Agalychnis annae",
        "familia": "Phyllomedusidae",
        "orden": "Anura",
        "estado_iucn": "EN",
        "endemica_cr": True,
        "venenosa": False,
        "nocturna": True,
        "arborea": True,
        "habitats": ["bosque_humedo", "bosque_nuboso"],
        "regiones_cr": ["Valle Central", "Cordillera"],
        "altitud_min": 600,
        "altitud_max": 1600,
        "longitud_max_cm": 9.0,
        "descripcion": "Endémica de Costa Rica. Ha perdido gran parte de su hábitat por la urbanización del Valle Central.",
        "curiosidad": "Solo existe en Costa Rica. No hay otra población en ningún otro país del mundo.",
        "imagen": "agalychnis_annae.jpg",
        "tags": ["endémica", "en peligro", "rana de árbol", "nocturna", "Valle Central"],
    },
    {
        "id": "agalychnis-lemur",
        "categoria": "anfibio",
        "subcategoria": "rana",
        "nombre_comun_es": "Rana Lémur",
        "nombre_comun_en": "Lemur Frog",
        "nombre_cientifico": "Agalychnis lemur",
        "familia": "Phyllomedusidae",
        "orden": "Anura",
        "estado_iucn": "CR",
        "endemica_cr": False,
        "venenosa": False,
        "nocturna": True,
        "arborea": True,
        "habitats": ["bosque_nuboso", "bosque_humedo"],
        "regiones_cr": ["Caribe", "Cordillera"],
        "altitud_min": 400,
        "altitud_max": 1500,
        "longitud_max_cm": 5.0,
        "descripcion": "Una de las ranas más amenazadas de Costa Rica. Devastada por el hongo quitridio.",
        "curiosidad": "Camina lentamente como un camaleón en lugar de saltar, lo que le da su nombre.",
        "imagen": "agalychnis_lemur.jpg",
        "tags": ["en peligro crítico", "rana de árbol", "hongo quitridio"],
    },
    {
        "id": "oophaga-pumilio",
        "categoria": "anfibio",
        "subcategoria": "rana",
        "nombre_comun_es": "Ranita Venenosa Fresa",
        "nombre_comun_en": "Strawberry Poison Dart Frog",
        "nombre_cientifico": "Oophaga pumilio",
        "familia": "Dendrobatidae",
        "orden": "Anura",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": True,
        "nocturna": False,
        "arborea": False,
        "habitats": ["bosque_humedo"],
        "regiones_cr": ["Caribe"],
        "altitud_min": 0,
        "altitud_max": 900,
        "longitud_max_cm": 2.5,
        "descripcion": "Pequeña pero poderosa. Su vivo color rojo advierte que es tóxica.",
        "curiosidad": "La hembra carga sus renacuajos uno por uno hasta bromelias y les lleva huevos infértiles como alimento.",
        "imagen": "oophaga_pumilio.jpg",
        "tags": ["venenosa", "colorida", "roja", "Tortuguero", "Caribe", "cuidado parental"],
    },
    {
        "id": "oophaga-granulifera",
        "categoria": "anfibio",
        "subcategoria": "rana",
        "nombre_comun_es": "Ranita Venenosa Granular",
        "nombre_comun_en": "Granular Poison Frog",
        "nombre_cientifico": "Oophaga granulifera",
        "familia": "Dendrobatidae",
        "orden": "Anura",
        "estado_iucn": "EN",
        "endemica_cr": True,
        "venenosa": True,
        "nocturna": False,
        "arborea": False,
        "habitats": ["bosque_humedo"],
        "regiones_cr": ["Pacífico Central", "Pacífico Sur"],
        "altitud_min": 0,
        "altitud_max": 500,
        "longitud_max_cm": 3.0,
        "descripcion": "Endémica del Pacífico Central. Coloración muy variable. En declive por destrucción del bosque costero.",
        "curiosidad": "Distintas poblaciones de diferentes ríos tienen colores tan distintos que se creían especies separadas.",
        "imagen": "oophaga_granulifera.jpg",
        "tags": ["endémica", "venenosa", "en peligro", "Pacífico", "dendrobátido"],
    },
    {
        "id": "dendrobates-auratus",
        "categoria": "anfibio",
        "subcategoria": "rana",
        "nombre_comun_es": "Ranita Venenosa Verde y Negra",
        "nombre_comun_en": "Green-and-black Poison Dart Frog",
        "nombre_cientifico": "Dendrobates auratus",
        "familia": "Dendrobatidae",
        "orden": "Anura",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": True,
        "nocturna": False,
        "arborea": False,
        "habitats": ["bosque_humedo"],
        "regiones_cr": ["Caribe", "Pacífico Central", "Pacífico Sur"],
        "altitud_min": 0,
        "altitud_max": 800,
        "longitud_max_cm": 4.0,
        "descripcion": "Patrón verde metálico y negro. Activa de día en el sotobosque.",
        "curiosidad": "Fue introducida en Hawái en 1932 y se estableció como especie invasora.",
        "imagen": "dendrobates_auratus.jpg",
        "tags": ["venenosa", "diurna", "colorida", "dendrobátido"],
    },
    {
        "id": "phyllobates-lugubris",
        "categoria": "anfibio",
        "subcategoria": "rana",
        "nombre_comun_es": "Ranita Venenosa Listada",
        "nombre_comun_en": "Stripe-bellied Poison Frog",
        "nombre_cientifico": "Phyllobates lugubris",
        "familia": "Dendrobatidae",
        "orden": "Anura",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": True,
        "nocturna": False,
        "arborea": False,
        "habitats": ["bosque_humedo"],
        "regiones_cr": ["Caribe"],
        "altitud_min": 0,
        "altitud_max": 500,
        "longitud_max_cm": 3.0,
        "descripcion": "Pequeña rana del Caribe con rayas amarillas sobre fondo oscuro.",
        "curiosidad": "El género Phyllobates es el único que produce batracotoxinas, los alcaloides más potentes en anfibios.",
        "imagen": "phyllobates_lugubris.jpg",
        "tags": ["venenosa", "Caribe", "diurna", "rayas"],
    },
    {
        "id": "espadarana-prosoblepon",
        "categoria": "anfibio",
        "subcategoria": "rana",
        "nombre_comun_es": "Rana de Vidrio Esmeralda",
        "nombre_comun_en": "Emerald Glass Frog",
        "nombre_cientifico": "Espadarana prosoblepon",
        "familia": "Centrolenidae",
        "orden": "Anura",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": False,
        "nocturna": True,
        "arborea": True,
        "habitats": ["bosque_humedo", "rio"],
        "regiones_cr": ["Caribe", "Pacífico Central", "Pacífico Sur"],
        "altitud_min": 0,
        "altitud_max": 1500,
        "longitud_max_cm": 3.5,
        "descripcion": "Piel ventral transparente donde se ven sus órganos y el corazón latiendo.",
        "curiosidad": "Los machos cuidan los huevos en el envés de las hojas, pateándolos para mantenerlos húmedos.",
        "imagen": "espadarana_prosoblepon.jpg",
        "tags": ["rana de vidrio", "transparente", "nocturna", "corrientes de agua"],
    },
    {
        "id": "hyalinobatrachium-fleischmanni",
        "categoria": "anfibio",
        "subcategoria": "rana",
        "nombre_comun_es": "Ranita de Vidrio de Fleischmann",
        "nombre_comun_en": "Fleischmann's Glass Frog",
        "nombre_cientifico": "Hyalinobatrachium fleischmanni",
        "familia": "Centrolenidae",
        "orden": "Anura",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": False,
        "nocturna": True,
        "arborea": True,
        "habitats": ["bosque_humedo", "bosque_seco", "rio"],
        "regiones_cr": ["Caribe", "Pacífico Norte", "Pacífico Central", "Valle Central"],
        "altitud_min": 0,
        "altitud_max": 1200,
        "longitud_max_cm": 2.8,
        "descripcion": "Una de las ranas de vidrio más comunes. Verde lima con puntos amarillos diminutos.",
        "curiosidad": "Son tan pequeñas que caben sobre la uña del pulgar.",
        "imagen": "hyalinobatrachium_fleischmanni.jpg",
        "tags": ["rana de vidrio", "pequeña", "nocturna", "río"],
    },
    {
        "id": "rhinella-marina",
        "categoria": "anfibio",
        "subcategoria": "sapo",
        "nombre_comun_es": "Sapo de Caña",
        "nombre_comun_en": "Cane Toad",
        "nombre_cientifico": "Rhinella marina",
        "familia": "Bufonidae",
        "orden": "Anura",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": True,
        "nocturna": True,
        "arborea": False,
        "habitats": ["jardines", "potrero", "zona_urbana", "bosque_humedo", "manglar"],
        "regiones_cr": ["Nacional"],
        "altitud_min": 0,
        "altitud_max": 1800,
        "longitud_max_cm": 23.0,
        "descripcion": "El sapo más grande de Costa Rica. Glándulas parotoideas con veneno potente. Muy común en jardines.",
        "curiosidad": "Su veneno puede matar perros. Si tu mascota lo muerde, enjuaga su boca y ve al veterinario.",
        "imagen": "rhinella_marina.jpg",
        "tags": ["común", "urbana", "venenosa", "grande", "jardines", "nocturna"],
    },
    {
        "id": "incilius-periglenes",
        "categoria": "anfibio",
        "subcategoria": "sapo",
        "nombre_comun_es": "Sapo Dorado",
        "nombre_comun_en": "Golden Toad",
        "nombre_cientifico": "Incilius periglenes",
        "familia": "Bufonidae",
        "orden": "Anura",
        "estado_iucn": "EX",
        "endemica_cr": True,
        "venenosa": False,
        "nocturna": False,
        "arborea": False,
        "habitats": ["bosque_nuboso"],
        "regiones_cr": ["Cordillera"],
        "altitud_min": 1500,
        "altitud_max": 1800,
        "longitud_max_cm": 5.0,
        "descripcion": "EXTINTO. Símbolo de CR y de Monteverde. Machos de naranja brillante. Visto por última vez en 1989.",
        "curiosidad": "Primer animal moderno cuya extinción fue atribuida directamente al cambio climático.",
        "imagen": "incilius_periglenes.jpg",
        "tags": ["extinto", "endémica", "Monteverde", "cambio climático", "historia"],
    },
    {
        "id": "incilius-holdridgei",
        "categoria": "anfibio",
        "subcategoria": "sapo",
        "nombre_comun_es": "Sapo de Holdridge",
        "nombre_comun_en": "Holdridge's Toad",
        "nombre_cientifico": "Incilius holdridgei",
        "familia": "Bufonidae",
        "orden": "Anura",
        "estado_iucn": "CR",
        "endemica_cr": True,
        "venenosa": False,
        "nocturna": False,
        "arborea": False,
        "habitats": ["bosque_nuboso"],
        "regiones_cr": ["Cordillera"],
        "altitud_min": 1700,
        "altitud_max": 2200,
        "longitud_max_cm": 5.0,
        "descripcion": "Sapo endémico de la Cordillera Central. Solo conocido de Braulio Carrillo y Volcán Barva.",
        "curiosidad": "Nombrado en honor a L.R. Holdridge, creador del sistema de zonas de vida.",
        "imagen": "incilius_holdridgei.jpg",
        "tags": ["endémica", "en peligro crítico", "Cordillera Central", "bosque nuboso"],
    },
    {
        "id": "smilisca-baudinii",
        "categoria": "anfibio",
        "subcategoria": "rana",
        "nombre_comun_es": "Rana de Árbol Mexicana",
        "nombre_comun_en": "Mexican Tree Frog",
        "nombre_cientifico": "Smilisca baudinii",
        "familia": "Hylidae",
        "orden": "Anura",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": False,
        "nocturna": True,
        "arborea": True,
        "habitats": ["bosque_seco", "potrero", "jardines", "bosque_humedo"],
        "regiones_cr": ["Pacífico Norte", "Pacífico Central", "Valle Central"],
        "altitud_min": 0,
        "altitud_max": 1200,
        "longitud_max_cm": 9.0,
        "descripcion": "Una de las ranas de árbol más grandes y sonoras del país. Común en jardines y zonas suburbanas.",
        "curiosidad": "Puede cambiar su tono de color entre gris claro y marrón oscuro según temperatura y estrés.",
        "imagen": "smilisca_baudinii.jpg",
        "tags": ["nocturna", "ruidosa", "rana de árbol", "jardines", "urbana"],
    },
    {
        "id": "engystomops-pustulosus",
        "categoria": "anfibio",
        "subcategoria": "rana",
        "nombre_comun_es": "Rana Túngara",
        "nombre_comun_en": "Túngara Frog",
        "nombre_cientifico": "Engystomops pustulosus",
        "familia": "Leptodactylidae",
        "orden": "Anura",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": False,
        "nocturna": True,
        "arborea": False,
        "habitats": ["potrero", "jardines", "zona_urbana", "bosque_seco"],
        "regiones_cr": ["Pacífico Norte", "Pacífico Central", "Valle Central"],
        "altitud_min": 0,
        "altitud_max": 1200,
        "longitud_max_cm": 3.5,
        "descripcion": "Famosa en ciencia por su llamado. El macho produce silbidos y 'chucks' para atraer hembras.",
        "curiosidad": "Más de 1,000 estudios científicos han usado esta rana para estudiar elección de pareja y evolución del comportamiento.",
        "imagen": "engystomops_pustulosus.jpg",
        "tags": ["famosa ciencia", "nocturna", "canto", "Pacífico seco"],
    },
    {
        "id": "leptodactylus-pentadactylus",
        "categoria": "anfibio",
        "subcategoria": "rana",
        "nombre_comun_es": "Rana Labio Blanco Grande",
        "nombre_comun_en": "South American Bullfrog",
        "nombre_cientifico": "Leptodactylus pentadactylus",
        "familia": "Leptodactylidae",
        "orden": "Anura",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": False,
        "nocturna": True,
        "arborea": False,
        "habitats": ["bosque_humedo"],
        "regiones_cr": ["Caribe", "Pacífico Sur"],
        "altitud_min": 0,
        "altitud_max": 600,
        "longitud_max_cm": 18.0,
        "descripcion": "Una de las ranas más grandes de Costa Rica. Marrón rojiza con labios blancos prominentes. Muy territorial.",
        "curiosidad": "Cuando se siente amenazada, se infla, muestra la coloración brillante de sus muslos y emite una secreción fétida.",
        "imagen": "leptodactylus_pentadactylus.jpg",
        "tags": ["grande", "nocturna", "bosque húmedo", "Caribe"],
    },
    {
        "id": "craugastor-fitzingeri",
        "categoria": "anfibio",
        "subcategoria": "rana",
        "nombre_comun_es": "Rana de Lluvia de Fitzinger",
        "nombre_comun_en": "Fitzinger's Rain Frog",
        "nombre_cientifico": "Craugastor fitzingeri",
        "familia": "Craugastoridae",
        "orden": "Anura",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": False,
        "nocturna": False,
        "arborea": False,
        "habitats": ["bosque_humedo", "bosque_seco", "potrero"],
        "regiones_cr": ["Nacional"],
        "altitud_min": 0,
        "altitud_max": 1500,
        "longitud_max_cm": 5.0,
        "descripcion": "Rana terrestre muy común. Desarrollo directo: las crías emergen como ranitas sin pasar por renacuajo.",
        "curiosidad": "Puede haber decenas de individuos por metro cuadrado, jugando un papel crucial en el ecosistema.",
        "imagen": "craugastor_fitzingeri.jpg",
        "tags": ["común", "terrestre", "hojarasca", "amplia distribución"],
    },
    {
        "id": "lithobates-vaillanti",
        "categoria": "anfibio",
        "subcategoria": "rana",
        "nombre_comun_es": "Rana Vaillant",
        "nombre_comun_en": "Vaillant's Frog",
        "nombre_cientifico": "Lithobates vaillanti",
        "familia": "Ranidae",
        "orden": "Anura",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": False,
        "nocturna": False,
        "arborea": False,
        "habitats": ["rio", "laguna", "bosque_humedo"],
        "regiones_cr": ["Caribe", "Zona Norte"],
        "altitud_min": 0,
        "altitud_max": 700,
        "longitud_max_cm": 13.0,
        "descripcion": "Una de las ranas más grandes. Verde con manchas oscuras. Siempre cerca de agua.",
        "curiosidad": "Su llamado nocturno resuena como un moo suave y puede escucharse desde cientos de metros.",
        "imagen": "lithobates_vaillanti.jpg",
        "tags": ["grande", "acuática", "Caribe", "Zona Norte", "río"],
    },

    # ═══════════════════════════════════════════════════
    #  ANFIBIOS — Salamandras (Caudata)
    # ═══════════════════════════════════════════════════

    {
        "id": "bolitoglossa-striatula",
        "categoria": "anfibio",
        "subcategoria": "salamandra",
        "nombre_comun_es": "Salamandra Tigre",
        "nombre_comun_en": "Tiger Salamander",
        "nombre_cientifico": "Bolitoglossa striatula",
        "familia": "Plethodontidae",
        "orden": "Caudata",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": False,
        "nocturna": True,
        "arborea": True,
        "habitats": ["bosque_humedo"],
        "regiones_cr": ["Caribe"],
        "altitud_min": 0,
        "altitud_max": 800,
        "longitud_max_cm": 14.0,
        "descripcion": "Salamandra sin pulmones con rayas naranjas sobre fondo negro. Arborícola con pies semipalmados.",
        "curiosidad": "Costa Rica tiene más de 40 especies de salamandras sin pulmones. Todas respiran a través de la piel.",
        "imagen": "bolitoglossa_striatula.jpg",
        "tags": ["salamandra", "sin pulmones", "nocturna", "arborícola", "Caribe"],
    },
    {
        "id": "bolitoglossa-robusta",
        "categoria": "anfibio",
        "subcategoria": "salamandra",
        "nombre_comun_es": "Salamandra Robusta",
        "nombre_comun_en": "Robust Climbing Salamander",
        "nombre_cientifico": "Bolitoglossa robusta",
        "familia": "Plethodontidae",
        "orden": "Caudata",
        "estado_iucn": "VU",
        "endemica_cr": True,
        "venenosa": False,
        "nocturna": True,
        "arborea": True,
        "habitats": ["bosque_nuboso"],
        "regiones_cr": ["Cordillera"],
        "altitud_min": 1400,
        "altitud_max": 3000,
        "longitud_max_cm": 20.0,
        "descripcion": "Una de las salamandras más grandes, endémica de las montañas de Costa Rica.",
        "curiosidad": "Puede sobrevivir en temperaturas muy frías, colonizando bosques de alta montaña.",
        "imagen": "bolitoglossa_robusta.jpg",
        "tags": ["endémica", "salamandra", "bosque nuboso", "montaña"],
    },

    # ═══════════════════════════════════════════════════
    #  ANFIBIOS — Cecilias (Gymnophiona)
    # ═══════════════════════════════════════════════════

    {
        "id": "gymnopis-multiplicata",
        "categoria": "anfibio",
        "subcategoria": "cecilia",
        "nombre_comun_es": "Cecilia Morada",
        "nombre_comun_en": "Purple Caecilian",
        "nombre_cientifico": "Gymnopis multiplicata",
        "familia": "Dermophiidae",
        "orden": "Gymnophiona",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": False,
        "nocturna": False,
        "arborea": False,
        "habitats": ["bosque_humedo", "potrero"],
        "regiones_cr": ["Caribe", "Pacífico Central", "Pacífico Sur"],
        "altitud_min": 0,
        "altitud_max": 1500,
        "longitud_max_cm": 60.0,
        "descripcion": "Anfibio sin patas que parece una lombriz. Vive completamente bajo tierra.",
        "curiosidad": "Las cecilias tienen pequeñas escamas en la piel, siendo los únicos anfibios con escamas.",
        "imagen": "gymnopis_multiplicata.jpg",
        "tags": ["cecilia", "sin patas", "subterránea", "rara", "anfibio inusual"],
    },
    {
        "id": "dermophis-costaricense",
        "categoria": "anfibio",
        "subcategoria": "cecilia",
        "nombre_comun_es": "Cecilia de Costa Rica",
        "nombre_comun_en": "Costa Rican Caecilian",
        "nombre_cientifico": "Dermophis costaricense",
        "familia": "Dermophiidae",
        "orden": "Gymnophiona",
        "estado_iucn": "LC",
        "endemica_cr": True,
        "venenosa": False,
        "nocturna": False,
        "arborea": False,
        "habitats": ["bosque_humedo"],
        "regiones_cr": ["Pacífico Sur", "Cordillera"],
        "altitud_min": 0,
        "altitud_max": 1200,
        "longitud_max_cm": 50.0,
        "descripcion": "Cecilia endémica de Costa Rica. Sin patas, vive bajo tierra en suelos húmedos del bosque.",
        "curiosidad": "Las crías de algunas cecilias se alimentan raspando la piel que desarrolla la madre (matrofagia).",
        "imagen": "dermophis_costaricense.jpg",
        "tags": ["endémica", "cecilia", "sin patas", "subterránea"],
    },

    # ═══════════════════════════════════════════════════
    #  REPTILES — Serpientes
    # ═══════════════════════════════════════════════════

    {
        "id": "bothrops-asper",
        "categoria": "reptil",
        "subcategoria": "serpiente",
        "nombre_comun_es": "Terciopelo",
        "nombre_comun_en": "Fer-de-Lance",
        "nombre_cientifico": "Bothrops asper",
        "familia": "Viperidae",
        "orden": "Squamata",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": True,
        "nocturna": True,
        "arborea": False,
        "habitats": ["bosque_humedo", "potrero", "bosque_seco", "manglar"],
        "regiones_cr": ["Nacional"],
        "altitud_min": 0,
        "altitud_max": 1500,
        "longitud_max_cm": 250.0,
        "descripcion": "La serpiente más peligrosa de Costa Rica. Responsable de la mayoría de accidentes ofídicos.",
        "curiosidad": "Ovovivípara: las crías nacen vivas y ya venenosas desde el primer minuto. Hasta 90 crías por parto.",
        "imagen": "bothrops_asper.jpg",
        "tags": ["peligrosa", "venenosa", "víbora", "nocturna", "críptica", "foseta"],
    },
    {
        "id": "crotalus-simus",
        "categoria": "reptil",
        "subcategoria": "serpiente",
        "nombre_comun_es": "Cascabel Centroamericana",
        "nombre_comun_en": "Mesoamerican Rattlesnake",
        "nombre_cientifico": "Crotalus simus",
        "familia": "Viperidae",
        "orden": "Squamata",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": True,
        "nocturna": False,
        "arborea": False,
        "habitats": ["bosque_seco", "potrero"],
        "regiones_cr": ["Pacífico Norte"],
        "altitud_min": 0,
        "altitud_max": 600,
        "longitud_max_cm": 180.0,
        "descripcion": "La única cascabel de Costa Rica. Veneno hemotóxico y neurotóxico. Habita Guanacaste.",
        "curiosidad": "Agrega un anillo a su cascabel cada muda de piel, pero no necesariamente una vez al año.",
        "imagen": "crotalus_simus.jpg",
        "tags": ["peligrosa", "venenosa", "cascabel", "Guanacaste", "bosque seco"],
    },
    {
        "id": "lachesis-stenophrys",
        "categoria": "reptil",
        "subcategoria": "serpiente",
        "nombre_comun_es": "Matabuey del Caribe",
        "nombre_comun_en": "Atlantic Forest Bushmaster",
        "nombre_cientifico": "Lachesis stenophrys",
        "familia": "Viperidae",
        "orden": "Squamata",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": True,
        "nocturna": True,
        "arborea": False,
        "habitats": ["bosque_humedo"],
        "regiones_cr": ["Caribe"],
        "altitud_min": 0,
        "altitud_max": 1000,
        "longitud_max_cm": 300.0,
        "descripcion": "La serpiente venenosa más grande del continente americano, supera los 3 metros.",
        "curiosidad": "Única víbora de América que incuba sus huevos. La hembra permanece en el nido semanas sin comer.",
        "imagen": "lachesis_stenophrys.jpg",
        "tags": ["grande", "venenosa", "peligrosa", "Caribe", "bushmaster", "rara"],
    },
    {
        "id": "lachesis-melanocephala",
        "categoria": "reptil",
        "subcategoria": "serpiente",
        "nombre_comun_es": "Matabuey del Pacífico",
        "nombre_comun_en": "Black-headed Bushmaster",
        "nombre_cientifico": "Lachesis melanocephala",
        "familia": "Viperidae",
        "orden": "Squamata",
        "estado_iucn": "VU",
        "endemica_cr": True,
        "venenosa": True,
        "nocturna": True,
        "arborea": False,
        "habitats": ["bosque_humedo"],
        "regiones_cr": ["Pacífico Sur"],
        "altitud_min": 0,
        "altitud_max": 800,
        "longitud_max_cm": 250.0,
        "descripcion": "Endémica del suroeste de Costa Rica. Cabeza y cola notoriamente negras. Habita Corcovado.",
        "curiosidad": "Endémica de uno de los puntos de mayor biodiversidad del planeta: el Pacífico Sur de CR.",
        "imagen": "lachesis_melanocephala.jpg",
        "tags": ["endémica", "peligrosa", "venenosa", "Corcovado", "Pacífico Sur"],
    },
    {
        "id": "porthidium-nasutum",
        "categoria": "reptil",
        "subcategoria": "serpiente",
        "nombre_comun_es": "Tamagá del Bosque",
        "nombre_comun_en": "Rainforest Hognosed Pitviper",
        "nombre_cientifico": "Porthidium nasutum",
        "familia": "Viperidae",
        "orden": "Squamata",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": True,
        "nocturna": True,
        "arborea": False,
        "habitats": ["bosque_humedo"],
        "regiones_cr": ["Caribe", "Pacífico Sur"],
        "altitud_min": 0,
        "altitud_max": 1200,
        "longitud_max_cm": 70.0,
        "descripcion": "Pequeña víbora con hocico levantado. Muy críptica entre la hojarasca.",
        "curiosidad": "Su nariz respingada podría ayudarla a maniobrar entre la hojarasca.",
        "imagen": "porthidium_nasutum.jpg",
        "tags": ["venenosa", "pequeña", "hojarasca", "hocico respingado"],
    },
    {
        "id": "micrurus-nigrocinctus",
        "categoria": "reptil",
        "subcategoria": "serpiente",
        "nombre_comun_es": "Coral Centroamericana",
        "nombre_comun_en": "Central American Coral Snake",
        "nombre_cientifico": "Micrurus nigrocinctus",
        "familia": "Elapidae",
        "orden": "Squamata",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": True,
        "nocturna": False,
        "arborea": False,
        "habitats": ["bosque_humedo", "bosque_seco", "potrero", "jardines"],
        "regiones_cr": ["Nacional"],
        "altitud_min": 0,
        "altitud_max": 1500,
        "longitud_max_cm": 130.0,
        "descripcion": "La coral más común. Anillos rojos, negros y amarillos. Veneno neurotóxico. Tímida.",
        "curiosidad": "En CR: rojo toca amarillo = CORAL VENENOSA. Rojo toca negro sin amarillo = falsa coral inofensiva.",
        "imagen": "micrurus_nigrocinctus.jpg",
        "tags": ["venenosa", "colorida", "coral", "neurotóxica", "tímida", "diurna"],
    },
    {
        "id": "boa-constrictor",
        "categoria": "reptil",
        "subcategoria": "serpiente",
        "nombre_comun_es": "Boa",
        "nombre_comun_en": "Boa Constrictor",
        "nombre_cientifico": "Boa constrictor",
        "familia": "Boidae",
        "orden": "Squamata",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": False,
        "nocturna": True,
        "arborea": True,
        "habitats": ["bosque_humedo", "bosque_seco", "potrero", "manglar", "zona_urbana"],
        "regiones_cr": ["Nacional"],
        "altitud_min": 0,
        "altitud_max": 1000,
        "longitud_max_cm": 400.0,
        "descripcion": "La serpiente más grande de Costa Rica. No venenosa, mata por constricción.",
        "curiosidad": "Las crías nacen vivas envueltas en membrana. Una hembra puede dar a luz más de 60 crías.",
        "imagen": "boa_constrictor.jpg",
        "tags": ["grande", "no venenosa", "constrictora", "común", "nocturna"],
    },
    {
        "id": "imantodes-cenchoa",
        "categoria": "reptil",
        "subcategoria": "serpiente",
        "nombre_comun_es": "Bejuquilla de Cabeza Grande",
        "nombre_comun_en": "Blunthead Tree Snake",
        "nombre_cientifico": "Imantodes cenchoa",
        "familia": "Colubridae",
        "orden": "Squamata",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": False,
        "nocturna": True,
        "arborea": True,
        "habitats": ["bosque_humedo"],
        "regiones_cr": ["Caribe", "Pacífico Central", "Pacífico Sur", "Zona Norte"],
        "altitud_min": 0,
        "altitud_max": 1400,
        "longitud_max_cm": 120.0,
        "descripcion": "Serpiente arborícola increíblemente delgada con cabeza grande y ojos enormes.",
        "curiosidad": "Puede extender un tercio de su cuerpo horizontalmente en el aire sin caerse.",
        "imagen": "imantodes_cenchoa.jpg",
        "tags": ["arborícola", "delgada", "ojos grandes", "nocturna", "no venenosa"],
    },
    {
        "id": "leptophis-ahaetulla",
        "categoria": "reptil",
        "subcategoria": "serpiente",
        "nombre_comun_es": "Lora Verde",
        "nombre_comun_en": "Parrot Snake",
        "nombre_cientifico": "Leptophis ahaetulla",
        "familia": "Colubridae",
        "orden": "Squamata",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": False,
        "nocturna": False,
        "arborea": True,
        "habitats": ["bosque_humedo", "bosque_seco", "potrero"],
        "regiones_cr": ["Nacional"],
        "altitud_min": 0,
        "altitud_max": 1500,
        "longitud_max_cm": 150.0,
        "descripcion": "Esbelta serpiente verde brillante, arborícola y diurna. Cuando se amenaza, abre la boca y se infla.",
        "curiosidad": "No es venenosa para humanos pero tiene saliva débilmente tóxica para inmovilizar presas.",
        "imagen": "leptophis_ahaetulla.jpg",
        "tags": ["verde", "arborícola", "diurna", "no venenosa", "rápida"],
    },
    {
        "id": "spilotes-pullatus",
        "categoria": "reptil",
        "subcategoria": "serpiente",
        "nombre_comun_es": "Mica",
        "nombre_comun_en": "Tiger Rat Snake",
        "nombre_cientifico": "Spilotes pullatus",
        "familia": "Colubridae",
        "orden": "Squamata",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": False,
        "nocturna": False,
        "arborea": True,
        "habitats": ["bosque_humedo", "bosque_seco", "potrero"],
        "regiones_cr": ["Nacional"],
        "altitud_min": 0,
        "altitud_max": 1500,
        "longitud_max_cm": 250.0,
        "descripcion": "Gran serpiente negra y amarilla. Muy activa de día. A menudo confundida con el terciopelo.",
        "curiosidad": "Aplana la cabeza, silba y golpea al amenazarse. A pesar de la actuación, es completamente inofensiva.",
        "imagen": "spilotes_pullatus.jpg",
        "tags": ["grande", "diurna", "no venenosa", "negra", "amarilla"],
    },
    {
        "id": "drymarchon-melanurus",
        "categoria": "reptil",
        "subcategoria": "serpiente",
        "nombre_comun_es": "Zopilota",
        "nombre_comun_en": "Central American Indigo Snake",
        "nombre_cientifico": "Drymarchon melanurus",
        "familia": "Colubridae",
        "orden": "Squamata",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": False,
        "nocturna": False,
        "arborea": False,
        "habitats": ["bosque_humedo", "bosque_seco", "potrero"],
        "regiones_cr": ["Nacional"],
        "altitud_min": 0,
        "altitud_max": 1200,
        "longitud_max_cm": 250.0,
        "descripcion": "Gran serpiente negra que devora casi cualquier animal, incluyendo serpientes venenosas.",
        "curiosidad": "Es inmune al veneno del terciopelo y otras víboras, y las caza activamente.",
        "imagen": "drymarchon_melanurus.jpg",
        "tags": ["grande", "diurna", "negra", "come serpientes", "inmune veneno", "no venenosa"],
    },
    {
        "id": "erythrolamprus-bizona",
        "categoria": "reptil",
        "subcategoria": "serpiente",
        "nombre_comun_es": "Falsa Coral",
        "nombre_comun_en": "False Coral Snake",
        "nombre_cientifico": "Erythrolamprus bizona",
        "familia": "Colubridae",
        "orden": "Squamata",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": False,
        "nocturna": False,
        "arborea": False,
        "habitats": ["bosque_humedo", "potrero"],
        "regiones_cr": ["Caribe", "Pacífico Sur"],
        "altitud_min": 0,
        "altitud_max": 1200,
        "longitud_max_cm": 90.0,
        "descripcion": "Serpiente inofensiva que imita a la coral. Anillos rojos y negros sin amarillo.",
        "curiosidad": "Si el rojo toca el negro sin amarillo, es falsa coral y completamente inofensiva.",
        "imagen": "erythrolamprus_bizona.jpg",
        "tags": ["falsa coral", "mimetismo", "inofensiva", "colorida"],
    },

    # ═══════════════════════════════════════════════════
    #  REPTILES — Iguanas y Lagartijas
    # ═══════════════════════════════════════════════════

    {
        "id": "basiliscus-plumifrons",
        "categoria": "reptil",
        "subcategoria": "iguana",
        "nombre_comun_es": "Basilisco Verde",
        "nombre_comun_en": "Plumed Basilisk",
        "nombre_cientifico": "Basiliscus plumifrons",
        "familia": "Corytophanidae",
        "orden": "Squamata",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": False,
        "nocturna": False,
        "arborea": True,
        "habitats": ["bosque_humedo", "rio"],
        "regiones_cr": ["Caribe", "Zona Norte"],
        "altitud_min": 0,
        "altitud_max": 800,
        "longitud_max_cm": 80.0,
        "descripcion": "El 'lagarto Jesucristo'. Verde brillante con cresta. Puede correr sobre el agua.",
        "curiosidad": "Corre sobre el agua a 8-9 km/h durante varios metros. Las crías son más hábiles que los adultos.",
        "imagen": "basiliscus_plumifrons.jpg",
        "tags": ["jesucristo", "verde", "camina sobre agua", "cresta", "Caribe"],
    },
    {
        "id": "basiliscus-basiliscus",
        "categoria": "reptil",
        "subcategoria": "iguana",
        "nombre_comun_es": "Basilisco Pardo",
        "nombre_comun_en": "Common Basilisk",
        "nombre_cientifico": "Basiliscus basiliscus",
        "familia": "Corytophanidae",
        "orden": "Squamata",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": False,
        "nocturna": False,
        "arborea": True,
        "habitats": ["bosque_seco", "bosque_humedo", "manglar", "rio"],
        "regiones_cr": ["Pacífico Norte", "Pacífico Central"],
        "altitud_min": 0,
        "altitud_max": 600,
        "longitud_max_cm": 75.0,
        "descripcion": "El basilisco del Pacífico. Marrón. También puede correr sobre el agua.",
        "curiosidad": "Puede bucear y permanecer bajo el agua hasta 30 minutos para escapar de depredadores.",
        "imagen": "basiliscus_basiliscus.jpg",
        "tags": ["basilisco", "marrón", "Pacífico", "camina sobre agua", "Guanacaste"],
    },
    {
        "id": "iguana-iguana",
        "categoria": "reptil",
        "subcategoria": "iguana",
        "nombre_comun_es": "Iguana Verde",
        "nombre_comun_en": "Green Iguana",
        "nombre_cientifico": "Iguana iguana",
        "familia": "Iguanidae",
        "orden": "Squamata",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": False,
        "nocturna": False,
        "arborea": True,
        "habitats": ["bosque_humedo", "bosque_seco", "manglar", "rio", "zona_urbana"],
        "regiones_cr": ["Nacional"],
        "altitud_min": 0,
        "altitud_max": 1000,
        "longitud_max_cm": 200.0,
        "descripcion": "La iguana más conocida. Verde brillante de joven, más gris de adulto. Herbívora.",
        "curiosidad": "Puede caer al agua desde más de 15 metros de altura sin lastimarse.",
        "imagen": "iguana_iguana.jpg",
        "tags": ["iguana", "verde", "grande", "herbívora", "arborícola", "río", "común"],
    },
    {
        "id": "ctenosaura-similis",
        "categoria": "reptil",
        "subcategoria": "iguana",
        "nombre_comun_es": "Garrobo Negro",
        "nombre_comun_en": "Black Spiny-tailed Iguana",
        "nombre_cientifico": "Ctenosaura similis",
        "familia": "Iguanidae",
        "orden": "Squamata",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": False,
        "nocturna": False,
        "arborea": True,
        "habitats": ["bosque_seco", "potrero", "zona_urbana"],
        "regiones_cr": ["Pacífico Norte", "Pacífico Central", "Valle Central"],
        "altitud_min": 0,
        "altitud_max": 800,
        "longitud_max_cm": 130.0,
        "descripcion": "El garrobo del Pacífico seco. Gris oscuro. Cola espinosa. El lagarto más rápido del mundo en tierra.",
        "curiosidad": "Se ha registrado corriendo a 34.9 km/h. ¡Más rápido que la mayoría de humanos!",
        "imagen": "ctenosaura_similis.jpg",
        "tags": ["garrobo", "rápido", "Pacífico seco", "Guanacaste", "omnívoro"],
    },
    {
        "id": "norops-biporcatus",
        "categoria": "reptil",
        "subcategoria": "lagartija",
        "nombre_comun_es": "Abaniquillo Gigante",
        "nombre_comun_en": "Giant Anole",
        "nombre_cientifico": "Norops biporcatus",
        "familia": "Dactyloidae",
        "orden": "Squamata",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": False,
        "nocturna": False,
        "arborea": True,
        "habitats": ["bosque_humedo"],
        "regiones_cr": ["Caribe", "Pacífico Central", "Zona Norte"],
        "altitud_min": 0,
        "altitud_max": 1000,
        "longitud_max_cm": 45.0,
        "descripcion": "El anolis más grande de CR. Verde brillante. Los machos tienen papada rosado-anaranjada.",
        "curiosidad": "Los machos hacen flexiones para mostrar su papada. El patrón es específico de cada especie.",
        "imagen": "norops_biporcatus.jpg",
        "tags": ["anolis", "verde", "arborícola", "papada", "bosque húmedo"],
    },

    # ═══════════════════════════════════════════════════
    #  REPTILES — Geckos
    # ═══════════════════════════════════════════════════

    {
        "id": "hemidactylus-frenatus",
        "categoria": "reptil",
        "subcategoria": "gecko",
        "nombre_comun_es": "Gecco de Casa",
        "nombre_comun_en": "Common House Gecko",
        "nombre_cientifico": "Hemidactylus frenatus",
        "familia": "Gekkonidae",
        "orden": "Squamata",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": False,
        "nocturna": True,
        "arborea": True,
        "habitats": ["zona_urbana", "jardines"],
        "regiones_cr": ["Nacional"],
        "altitud_min": 0,
        "altitud_max": 1500,
        "longitud_max_cm": 14.0,
        "descripcion": "La lagartija más común de las casas. Sus dedos adhesivos le permiten caminar en paredes y techos.",
        "curiosidad": "Sus dedos usan fuerzas de Van der Waals para adherirse, no pegamento. Con un solo dedo soporta su peso.",
        "imagen": "hemidactylus_frenatus.jpg",
        "tags": ["gecco", "casa", "nocturno", "paredes", "introducida", "común"],
    },
    {
        "id": "thecadactylus-rapicauda",
        "categoria": "reptil",
        "subcategoria": "gecko",
        "nombre_comun_es": "Gecco de Cola de Nabo",
        "nombre_comun_en": "Turnip-tailed Gecko",
        "nombre_cientifico": "Thecadactylus rapicauda",
        "familia": "Phyllodactylidae",
        "orden": "Squamata",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": False,
        "nocturna": True,
        "arborea": True,
        "habitats": ["bosque_humedo", "zona_urbana"],
        "regiones_cr": ["Caribe", "Pacífico Sur", "Zona Norte"],
        "altitud_min": 0,
        "altitud_max": 900,
        "longitud_max_cm": 25.0,
        "descripcion": "El gecko más grande de Costa Rica. Cola gruesa y corta en forma de nabo cuando está regenerada.",
        "curiosidad": "La cola regenerada tiene cartílago en vez de hueso y es más corta y rechoncha, de ahí el apodo.",
        "imagen": "thecadactylus_rapicauda.jpg",
        "tags": ["gecco", "grande", "nocturno", "cola nabo", "arborícola"],
    },
    {
        "id": "gonatodes-albogularis",
        "categoria": "reptil",
        "subcategoria": "gecko",
        "nombre_comun_es": "Gecco de Cabeza Amarilla",
        "nombre_comun_en": "Yellow-headed Gecko",
        "nombre_cientifico": "Gonatodes albogularis",
        "familia": "Sphaerodactylidae",
        "orden": "Squamata",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": False,
        "nocturna": False,
        "arborea": True,
        "habitats": ["bosque_seco", "zona_urbana", "jardines"],
        "regiones_cr": ["Pacífico Norte", "Pacífico Central", "Valle Central"],
        "altitud_min": 0,
        "altitud_max": 1200,
        "longitud_max_cm": 8.0,
        "descripcion": "Pequeño gecko diurno. El macho tiene cabeza naranja y cuerpo azul-negro.",
        "curiosidad": "Uno de los pocos geckos diurnos. Sus pupilas son redondas, no en hendidura como los nocturnos.",
        "imagen": "gonatodes_albogularis.jpg",
        "tags": ["gecco", "diurno", "naranja", "pequeño", "jardines", "Valle Central"],
    },
    {
        "id": "holcosus-festivus",
        "categoria": "reptil",
        "subcategoria": "lagartija",
        "nombre_comun_es": "Chisbala",
        "nombre_comun_en": "Middle American Ameiva",
        "nombre_cientifico": "Holcosus festivus",
        "familia": "Teiidae",
        "orden": "Squamata",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": False,
        "nocturna": False,
        "arborea": False,
        "habitats": ["bosque_humedo", "potrero", "bosque_seco"],
        "regiones_cr": ["Nacional"],
        "altitud_min": 0,
        "altitud_max": 1500,
        "longitud_max_cm": 35.0,
        "descripcion": "Lagartija terrestre muy activa y veloz. Macho azulado brillante en el costado.",
        "curiosidad": "A pesar de su pequeño tamaño, muerde muy fuerte. Sus mordidas suelen sorprender por lo dolorosas.",
        "imagen": "holcosus_festivus.jpg",
        "tags": ["chisbala", "terrestre", "activa", "azul", "rápida", "común"],
    },

    # ═══════════════════════════════════════════════════
    #  REPTILES — Cocodrilos
    # ═══════════════════════════════════════════════════

    {
        "id": "crocodylus-acutus",
        "categoria": "reptil",
        "subcategoria": "cocodrilo",
        "nombre_comun_es": "Cocodrilo Americano",
        "nombre_comun_en": "American Crocodile",
        "nombre_cientifico": "Crocodylus acutus",
        "familia": "Crocodylidae",
        "orden": "Crocodylia",
        "estado_iucn": "VU",
        "endemica_cr": False,
        "venenosa": False,
        "nocturna": False,
        "arborea": False,
        "habitats": ["rio", "manglar", "laguna"],
        "regiones_cr": ["Caribe", "Pacífico Norte", "Pacífico Central", "Pacífico Sur"],
        "altitud_min": 0,
        "altitud_max": 200,
        "longitud_max_cm": 600.0,
        "descripcion": "El mayor reptil depredador. Puede superar los 5-6 metros. El Río Tárcoles tiene una de las poblaciones más densas del mundo.",
        "curiosidad": "Su mordida es la más potente del reino animal. No puede masticar: traga sus presas enteras.",
        "imagen": "crocodylus_acutus.jpg",
        "tags": ["cocodrilo", "grande", "peligroso", "Tárcoles", "río", "manglar"],
    },
    {
        "id": "caiman-crocodilus",
        "categoria": "reptil",
        "subcategoria": "cocodrilo",
        "nombre_comun_es": "Caimán de Anteojos",
        "nombre_comun_en": "Spectacled Caiman",
        "nombre_cientifico": "Caiman crocodilus",
        "familia": "Alligatoridae",
        "orden": "Crocodylia",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": False,
        "nocturna": True,
        "arborea": False,
        "habitats": ["rio", "laguna", "zona_urbana"],
        "regiones_cr": ["Caribe", "Zona Norte", "Pacífico Sur"],
        "altitud_min": 0,
        "altitud_max": 400,
        "longitud_max_cm": 250.0,
        "descripcion": "El cocodrilo más común de las tierras bajas húmedas. La cresta ósea entre sus ojos le da el apodo 'anteojos'.",
        "curiosidad": "Se distingue del cocodrilo americano por su hocico más corto y ancho.",
        "imagen": "caiman_crocodilus.jpg",
        "tags": ["caimán", "Tortuguero", "Caribe", "Zona Norte", "nocturno"],
    },

    # ═══════════════════════════════════════════════════
    #  REPTILES — Tortugas Marinas
    # ═══════════════════════════════════════════════════

    {
        "id": "dermochelys-coriacea",
        "categoria": "reptil",
        "subcategoria": "tortuga_marina",
        "nombre_comun_es": "Baula",
        "nombre_comun_en": "Leatherback Sea Turtle",
        "nombre_cientifico": "Dermochelys coriacea",
        "familia": "Dermochelyidae",
        "orden": "Testudines",
        "estado_iucn": "VU",
        "endemica_cr": False,
        "venenosa": False,
        "nocturna": True,
        "arborea": False,
        "habitats": ["playa"],
        "regiones_cr": ["Caribe", "Pacífico Norte"],
        "altitud_min": 0,
        "altitud_max": 0,
        "longitud_max_cm": 200.0,
        "descripcion": "La tortuga más grande del mundo. Anida en Tortuguero, Gandoca y Playa Grande.",
        "curiosidad": "Puede regular su temperatura hasta 18°C por encima del agua, siendo casi de sangre caliente.",
        "imagen": "dermochelys_coriacea.jpg",
        "tags": ["baula", "grande", "tortuga marina", "anidación", "Tortuguero", "Las Baulas"],
    },
    {
        "id": "chelonia-mydas",
        "categoria": "reptil",
        "subcategoria": "tortuga_marina",
        "nombre_comun_es": "Tortuga Verde",
        "nombre_comun_en": "Green Sea Turtle",
        "nombre_cientifico": "Chelonia mydas",
        "familia": "Cheloniidae",
        "orden": "Testudines",
        "estado_iucn": "EN",
        "endemica_cr": False,
        "venenosa": False,
        "nocturna": True,
        "arborea": False,
        "habitats": ["playa"],
        "regiones_cr": ["Caribe"],
        "altitud_min": 0,
        "altitud_max": 0,
        "longitud_max_cm": 153.0,
        "descripcion": "Tortuguero es uno de los sitios de anidación más importantes del Atlántico.",
        "curiosidad": "Navegan miles de kilómetros usando el campo magnético de la Tierra para volver a su playa de nacimiento.",
        "imagen": "chelonia_mydas.jpg",
        "tags": ["tortuga marina", "Tortuguero", "Caribe", "en peligro", "anidación"],
    },
    {
        "id": "lepidochelys-olivacea",
        "categoria": "reptil",
        "subcategoria": "tortuga_marina",
        "nombre_comun_es": "Tortuga Lora",
        "nombre_comun_en": "Olive Ridley Sea Turtle",
        "nombre_cientifico": "Lepidochelys olivacea",
        "familia": "Cheloniidae",
        "orden": "Testudines",
        "estado_iucn": "VU",
        "endemica_cr": False,
        "venenosa": False,
        "nocturna": True,
        "arborea": False,
        "habitats": ["playa"],
        "regiones_cr": ["Pacífico Norte"],
        "altitud_min": 0,
        "altitud_max": 0,
        "longitud_max_cm": 80.0,
        "descripcion": "La tortuga marina más abundante. Famosa por sus 'arribadas' masivas en Ostional.",
        "curiosidad": "Durante una arribada en Ostional pueden anidar hasta 500,000 tortugas en una sola semana.",
        "imagen": "lepidochelys_olivacea.jpg",
        "tags": ["lora", "Ostional", "Guanacaste", "arribada", "Pacífico", "tortuga marina"],
    },
    {
        "id": "eretmochelys-imbricata",
        "categoria": "reptil",
        "subcategoria": "tortuga_marina",
        "nombre_comun_es": "Tortuga Carey",
        "nombre_comun_en": "Hawksbill Sea Turtle",
        "nombre_cientifico": "Eretmochelys imbricata",
        "familia": "Cheloniidae",
        "orden": "Testudines",
        "estado_iucn": "CR",
        "endemica_cr": False,
        "venenosa": False,
        "nocturna": True,
        "arborea": False,
        "habitats": ["playa"],
        "regiones_cr": ["Caribe", "Pacífico Norte"],
        "altitud_min": 0,
        "altitud_max": 0,
        "longitud_max_cm": 114.0,
        "descripcion": "En peligro crítico. Pico estrecho y curvo para extraer esponjas de arrecifes.",
        "curiosidad": "Come esponjas tóxicas. Su carne puede volverse tóxica para las personas.",
        "imagen": "eretmochelys_imbricata.jpg",
        "tags": ["carey", "en peligro crítico", "coral", "tortuga marina"],
    },

    # ═══════════════════════════════════════════════════
    #  REPTILES — Tortugas de Agua Dulce y Tierra
    # ═══════════════════════════════════════════════════

    {
        "id": "rhinoclemmys-pulcherrima",
        "categoria": "reptil",
        "subcategoria": "tortuga_terrestre",
        "nombre_comun_es": "Tortuga Pintada",
        "nombre_comun_en": "Painted Wood Turtle",
        "nombre_cientifico": "Rhinoclemmys pulcherrima",
        "familia": "Geoemydidae",
        "orden": "Testudines",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": False,
        "nocturna": False,
        "arborea": False,
        "habitats": ["bosque_seco", "bosque_humedo", "rio"],
        "regiones_cr": ["Pacífico Norte", "Pacífico Central"],
        "altitud_min": 0,
        "altitud_max": 800,
        "longitud_max_cm": 25.0,
        "descripcion": "La tortuga terrestre más colorida de Costa Rica. Caparazón con adornos rojos y naranjas.",
        "curiosidad": "Es tan colorida que la compran ilegalmente como mascota, presionando sus poblaciones.",
        "imagen": "rhinoclemmys_pulcherrima.jpg",
        "tags": ["tortuga", "colorida", "Pacífico", "río", "terrestre"],
    },
    {
        "id": "rhinoclemmys-funerea",
        "categoria": "reptil",
        "subcategoria": "tortuga_terrestre",
        "nombre_comun_es": "Tortuga Negra de Río",
        "nombre_comun_en": "Black Wood Turtle",
        "nombre_cientifico": "Rhinoclemmys funerea",
        "familia": "Geoemydidae",
        "orden": "Testudines",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": False,
        "nocturna": False,
        "arborea": False,
        "habitats": ["rio", "bosque_humedo"],
        "regiones_cr": ["Caribe", "Zona Norte"],
        "altitud_min": 0,
        "altitud_max": 600,
        "longitud_max_cm": 32.0,
        "descripcion": "Tortuga negra semi-acuática con rayas amarillas. La de agua dulce más grande de CR.",
        "curiosidad": "Puede trepar ramas inclinadas sobre el agua para asolearse. Si cae, nada perfectamente.",
        "imagen": "rhinoclemmys_funerea.jpg",
        "tags": ["tortuga", "acuática", "Caribe", "río", "negra"],
    },
    {
        "id": "kinosternon-leucostomum",
        "categoria": "reptil",
        "subcategoria": "tortuga_terrestre",
        "nombre_comun_es": "Pecho de Queque",
        "nombre_comun_en": "White-lipped Mud Turtle",
        "nombre_cientifico": "Kinosternon leucostomum",
        "familia": "Kinosternidae",
        "orden": "Testudines",
        "estado_iucn": "LC",
        "endemica_cr": False,
        "venenosa": False,
        "nocturna": False,
        "arborea": False,
        "habitats": ["rio", "laguna", "potrero", "bosque_humedo"],
        "regiones_cr": ["Caribe", "Zona Norte", "Pacífico Central", "Pacífico Sur"],
        "altitud_min": 0,
        "altitud_max": 800,
        "longitud_max_cm": 17.0,
        "descripcion": "Pequeña tortuga con plastrón abisagrado que le permite cerrarse completamente.",
        "curiosidad": "Puede caminar kilómetros por tierra durante la época seca para encontrar nuevos cuerpos de agua.",
        "imagen": "kinosternon_leucostomum.jpg",
        "tags": ["tortuga", "pequeña", "agua dulce", "común", "plastrón bisagra"],
    },
]
